### ISSUE TITLE
Strange behaviour when adding levels of exhaustion, especially after just loading, a period of time when not used and duplicate tokens

### ISSUE THREAD

**Issue by YenBenGrey** [krbz999/alternative-exhaustion-5e#1]
Hey Zhell, something really strange is happening with your Exhaustion Mod or ALTEX or DM (?).

When I load up the world, and try to add a level of exhaustion via either the token HUD or the macro it does not add a level of exhaustion.

However when I go in to the character sheet (dnd5e v3.0.4) and click on the 1st level of exhaustion pip, nothing happens. Then when I click on the 2nd level of exhaustion pip it applies the correct exhaustion. Then I click on 2nd level again it goes away and 1st level stays.

From then on you can add exhaustion levels via the HUD or the macro. 

There are no errors in console and I have tested this with just ALTEX on only. All other modules turned off. 

Then after a period of time or a reload the world it seems to reset and I can't add exhaustion until I have done that little ritual above again. (The add 2nd level, delete 2nd level ritual), Not sure if this helps any investigation but if I then go to another scene and drag a PC out that has got a token on another scene, the same thing happens, you can't add exhaustion to this other token until you do that little ritual.

Whilst I have been writing this, I went back to the world, so what, five minutes, and it has 'reset' to not being able to add exhaustion again via the HUD or macro. Do the 'ritual' and it works again.

**Comment by krbz999** [comment]
Either a system or browser issue.
