### ISSUE TITLE
Exhaustion does not seem to remove penalties when set to Exhaustion 0

### ISSUE THREAD

**Issue by rjbprime** [krbz999/alternative-exhaustion-5e#2]
Hello,

I have installed this mod on FoundryVTT 11.315, DND5 3.1.2, and both Modern and Legacy Character sheets. When setting exhaustion with the special traits, works fine. When attempting to remove, it keeps last selected exhaustion and associated penalties. I can confirm this is the case when switching to Legacy Character Sheet to test, typing any number in the Exhaustion box except 0, works. Typing 0 afterwards, does not end the penalties.

Can this be repro'd on your end, and if so, can it be fixed?

Kind regards.

**Comment by krbz999** [comment]
Sounds like the instructions on the readme were not followed. Not able to reproduce.

**Comment by rjbprime** [comment]
Does one have to remove the code when Exhaustion is 0? As that was the only way I could get it to reset.

**Comment by krbz999** [comment]
Then your exhaustion was not 0.

Github is not for troubleshooting. Please enter the discord server and provide screenshots of what you are setting up, in a single-module environment.

**Comment by krbz999** [comment]
Resolved. The issue was "Convenient Effects".
