### ISSUE TITLE
Old exhaustion rules are still being applied/tracked at the same time as new ones

### ISSUE THREAD

**Issue by NdranC** [krbz999/alternative-exhaustion-5e#3]
I'm using the non manual mode and giving one exhaustion to a token works correctly as far as OneDnD rules. The problem is that it's also giving disadvantage to all skill checks. The same happens with higher levels of exhaustion. It's applying both the new penalty and the old one (with the exception of the speed penalty for some reason).

This is with Foundry v11, DnD 5e 3.2.0 and your latest version.
![Screenshot from 2024-06-10 06-20-47](https://github.com/krbz999/alternative-exhaustion-5e/assets/27837113/2f054048-3986-4fca-b5d3-020627957fab)

**Comment by krbz999** [comment]
Given that the system does not do this, you have a different module causing this issue.

You should *always* see if an issue occurs with only the singular module enabled.

**Comment by NdranC** [comment]
Yeah. Sorry. 

End up with so many modules installed that I forget which one does what. Turns out it was a weird interaction with Rest Recovery 5e. It was on and off so it was hard to track so I just defaulted to this mod but I should've tested first with Find the Culprit.
